program: train.py
name: sweepdemo
project: corrupt_mnist  # change this
entity: vastian4  # change this
metric:
    goal: minimize
    name: validation_loss
parameters:
    learning_rate:
        min: 0.001
        max: 0.1
        distribution: log_uniform
    batch_size:
        values: [16, 32, 64]
    epochs:
        values: [3, 5, 7]
run_cap: 10